// Cross-platform parity: replay data/parity_fixtures.json (generated by
// parity_fixtures.py from the Python engine) through the Kotlin engine and
// require identical behaviour. CI sets PARITY_FIXTURES; without it the
// test is skipped (Assume) so plain `./gradlew test` still works.
package com.fekitech.gymcoach.core

import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assume.assumeTrue
import org.junit.Test
import java.io.File

class ParityTest {

    private val tolerance = 1e-4

    private fun fixtures(): JSONObject {
        val path = System.getenv("PARITY_FIXTURES")
            ?: System.getProperty("parity.fixtures")
        assumeTrue("PARITY_FIXTURES not set — parity replay runs in CI",
                   path != null && File(path).exists())
        val root = JSONObject(File(path!!).readText())
        assertEquals("fixture schema changed — update ParityTest",
                     1, root.getInt("schema"))
        return root
    }

    @Test
    fun repCounterParity() {
        val root = fixtures()
        val cases = root.getJSONArray("fsm_cases")
        for (ci in 0 until cases.length()) {
            val c = cases.getJSONObject(ci)
            val name = c.getString("name")
            val fps = c.getInt("fps").toDouble()
            val spec = specs[c.getString("exercise")]
                ?: error("$name: unknown exercise in Kotlin specs")
            val angles = c.getJSONArray("angles")
            val expected = c.getJSONObject("expected")
            val counter = RepCounter(spec)
            val reps = mutableListOf<RepEvent>()
            for (i in 0 until angles.length()) {
                counter.update(angles.getDouble(i), i / fps)?.let { reps.add(it) }
            }
            assertEquals("$name: rep count drifted",
                         expected.getInt("count"), counter.count)
            assertEquals("$name: final FSM state drifted",
                         expected.getString("final_state"), counter.state.label)
            val expReps = expected.getJSONArray("reps")
            assertEquals(name, expReps.length(), reps.size)
            for (i in 0 until expReps.length()) {
                val exp = expReps.getJSONObject(i)
                val got = reps[i]
                val n = exp.getInt("n")
                assertEquals("$name rep", n, got.count)
                assertEquals("$name rep $n duration",
                             exp.getDouble("duration_s"), got.duration, tolerance)
                assertEquals("$name rep $n ecc",
                             exp.getDouble("ecc_s"), got.eccentricS, tolerance)
                assertEquals("$name rep $n con",
                             exp.getDouble("con_s"), got.concentricS, tolerance)
                assertEquals("$name rep $n minAngle",
                             exp.getDouble("min_angle"), got.minAngle, tolerance)
                assertEquals("$name rep $n fullDepth",
                             exp.getBoolean("full_depth"), got.fullDepth)
            }
        }
    }

    @Test
    fun plankParity() {
        val root = fixtures()
        val cases = root.getJSONArray("plank_cases")
        for (ci in 0 until cases.length()) {
            val c = cases.getJSONObject(ci)
            val name = c.getString("name")
            val fps = c.getInt("fps").toDouble()
            val line = c.getJSONArray("body_line")
            val expected = c.getJSONObject("expected")
            val plank = PlankTracker()
            var cues = 0
            for (i in 0 until line.length()) {
                if (plank.update(line.getDouble(i), i / fps)) cues += 1
            }
            assertEquals("$name total",
                         expected.getDouble("total_s"), plank.total, tolerance)
            assertEquals("$name best",
                         expected.getDouble("best_s"), plank.best, tolerance)
            assertEquals("$name cues", expected.getInt("cues"), cues)
        }
    }

    @Test
    fun autoDetectParity() {
        val root = fixtures()
        val cases = root.getJSONArray("detect_cases")
        for (ci in 0 until cases.length()) {
            val c = cases.getJSONObject(ci)
            val name = c.getString("name")
            val fps = c.getInt("fps").toDouble()
            val frames = c.getJSONArray("frames")
            val expected = c.getJSONObject("expected")
            val det = AutoDetector()
            var detected: String? = null
            var atFrame: Int? = null
            for (i in 0 until frames.length()) {
                val f = frames.getJSONObject(i)
                val feat = FrameFeatures(
                    trunk = f.getDouble("trunk"),
                    knee = f.getDouble("knee"),
                    elbow = f.getDouble("elbow"),
                    hip = f.getDouble("hip"),
                    shoY = f.getDouble("sho_y"),
                    wriY = f.getDouble("wri_y"),
                    torso = f.getDouble("torso"),
                    overhead = f.getBoolean("overhead"),
                    kneeSplit = f.getDouble("knee_split"),
                )
                val got = det.update(feat, i / fps)
                if (got != null && detected == null) {
                    detected = got
                    atFrame = i
                }
            }
            val expExercise =
                if (expected.isNull("exercise")) null
                else expected.getString("exercise")
            assertEquals("$name: detection drifted", expExercise, detected)
            if (!expected.isNull("at_frame")) {
                assertEquals("$name: detection timing drifted",
                             expected.getInt("at_frame"), atFrame)
            }
        }
    }
}
