// Cross-platform parity: replay data/parity_fixtures.json (generated by
// parity_fixtures.py from the Python engine) through the Swift engine and
// require identical behaviour. CI sets PARITY_FIXTURES to the repo file;
// without it the suite skips so `swift test` still works standalone.

import XCTest
@testable import CoachCore

final class ParityTests: XCTestCase {

    struct Fixtures {
        let tolerance: Double
        let fsm: [[String: Any]]
        let plank: [[String: Any]]
        let detect: [[String: Any]]
    }

    private func loadFixtures() throws -> Fixtures {
        guard let path = ProcessInfo.processInfo.environment["PARITY_FIXTURES"],
              FileManager.default.fileExists(atPath: path) else {
            throw XCTSkip("PARITY_FIXTURES not set — parity replay runs in CI")
        }
        let data = try Data(contentsOf: URL(fileURLWithPath: path))
        let root = try JSONSerialization.jsonObject(with: data) as! [String: Any]
        XCTAssertEqual(root["schema"] as? Int, 1, "fixture schema changed — update ParityTests")
        return Fixtures(
            tolerance: root["tolerance"] as? Double ?? 1e-4,
            fsm: root["fsm_cases"] as! [[String: Any]],
            plank: root["plank_cases"] as! [[String: Any]],
            detect: root["detect_cases"] as! [[String: Any]])
    }

    func testRepCounterParity() throws {
        let fx = try loadFixtures()
        for c in fx.fsm {
            let name = c["name"] as! String
            let exercise = c["exercise"] as! String
            let fps = Double(c["fps"] as! Int)
            let angles = (c["angles"] as! [Any]).map { ($0 as! NSNumber).doubleValue }
            let expected = c["expected"] as! [String: Any]
            guard let spec = specs[exercise] else {
                XCTFail("\(name): unknown exercise \(exercise) in Swift specs")
                continue
            }
            let counter = RepCounter(spec: spec)
            var reps: [RepEvent] = []
            for (i, a) in angles.enumerated() {
                if let ev = counter.update(angle: a, t: Double(i) / fps) {
                    reps.append(ev)
                }
            }
            XCTAssertEqual(counter.count, expected["count"] as! Int,
                           "\(name): rep count drifted")
            XCTAssertEqual(counter.state.rawValue,
                           expected["final_state"] as! String,
                           "\(name): final FSM state drifted")
            let expReps = expected["reps"] as! [[String: Any]]
            XCTAssertEqual(reps.count, expReps.count, name)
            for (got, exp) in zip(reps, expReps) {
                let n = exp["n"] as! Int
                XCTAssertEqual(got.count, n, name)
                XCTAssertEqual(got.duration, (exp["duration_s"] as! NSNumber).doubleValue,
                               accuracy: fx.tolerance, "\(name) rep \(n) duration")
                XCTAssertEqual(got.eccentricS, (exp["ecc_s"] as! NSNumber).doubleValue,
                               accuracy: fx.tolerance, "\(name) rep \(n) ecc")
                XCTAssertEqual(got.concentricS, (exp["con_s"] as! NSNumber).doubleValue,
                               accuracy: fx.tolerance, "\(name) rep \(n) con")
                XCTAssertEqual(got.minAngle, (exp["min_angle"] as! NSNumber).doubleValue,
                               accuracy: fx.tolerance, "\(name) rep \(n) minAngle")
                XCTAssertEqual(got.fullDepth, exp["full_depth"] as! Bool,
                               "\(name) rep \(n) fullDepth")
            }
        }
    }

    func testPlankParity() throws {
        let fx = try loadFixtures()
        for c in fx.plank {
            let name = c["name"] as! String
            let fps = Double(c["fps"] as! Int)
            let line = (c["body_line"] as! [Any]).map { ($0 as! NSNumber).doubleValue }
            let expected = c["expected"] as! [String: Any]
            let plank = PlankTracker()
            var cues = 0
            for (i, v) in line.enumerated() {
                if plank.update(bodyLine: v, t: Double(i) / fps) { cues += 1 }
            }
            XCTAssertEqual(plank.total, (expected["total_s"] as! NSNumber).doubleValue,
                           accuracy: fx.tolerance, "\(name) total")
            XCTAssertEqual(plank.best, (expected["best_s"] as! NSNumber).doubleValue,
                           accuracy: fx.tolerance, "\(name) best")
            XCTAssertEqual(cues, expected["cues"] as! Int, "\(name) cues")
        }
    }

    func testAutoDetectParity() throws {
        let fx = try loadFixtures()
        for c in fx.detect {
            let name = c["name"] as! String
            let fps = Double(c["fps"] as! Int)
            let frames = c["frames"] as! [[String: Any]]
            let expected = c["expected"] as! [String: Any]
            let det = AutoDetector()
            var detected: String?
            var atFrame: Int?
            for (i, f) in frames.enumerated() {
                let feat = FrameFeatures(
                    trunk: (f["trunk"] as! NSNumber).doubleValue,
                    knee: (f["knee"] as! NSNumber).doubleValue,
                    elbow: (f["elbow"] as! NSNumber).doubleValue,
                    hip: (f["hip"] as! NSNumber).doubleValue,
                    shoY: (f["sho_y"] as! NSNumber).doubleValue,
                    wriY: (f["wri_y"] as! NSNumber).doubleValue,
                    torso: (f["torso"] as! NSNumber).doubleValue,
                    overhead: f["overhead"] as! Bool,
                    kneeSplit: (f["knee_split"] as! NSNumber).doubleValue)
                if let got = det.update(feat, t: Double(i) / fps),
                   detected == nil {
                    detected = got
                    atFrame = i
                }
            }
            let expExercise = expected["exercise"] as? String   // null -> nil
            XCTAssertEqual(detected, expExercise, "\(name): detection drifted")
            if let expAt = expected["at_frame"] as? Int {
                XCTAssertEqual(atFrame, expAt, "\(name): detection timing drifted")
            }
        }
    }
}
